### ISSUE TITLE
[Bug] Remove all Promise.resolve() `hint-sri`

### ISSUE THREAD

**Issue by molant** [webhintio/hint#2035]
With the changes in #1943 the validations are `sync` now but we are still using `Promise.resolve` in quite a few places. We should remove them where we can.

**Comment by chrisguttandin** [comment]
Hi @molant, maybe this is somehow related. I noticed that the recent update to hint-sri introduced a regression for me. No matter which source gets checked the hint always reports that the expected hash should be `sha384-pCIgIQDl29ZunYA79Fgog9IN7UIB/qh05ZuzOCXHxCoFQ9qlEpRrWcSzhMWD8IEK`. It's always the same hash in my case no matter which source is checked. I therefore guess the hint is not waiting for source to be loaded anymore before computing the hash. Instead it seems to always compute the hash of the same default value. However I had no time yet to take a closer look. I hope this makes sense.

**Comment by molant** [comment]
What version of `hint-sri` are you running? I just published a new version today because `ignoredUrls` wasn't being honored (https://github.com/webhintio/hint/pull/2023).

Do you have a url with the repro? If you don't want to share it publicly you can DM it via twitter.

**Comment by chrisguttandin** [comment]
Hi @molant, I tried to narrow down the problem today.

I can confirm that everything still works as expected with hint v4.4.0, @hint/hint-sri v3.0.2 and @hint/connector-chrome v3.0.0.

When I update everything to the latest version I still get an error although it's a different one now. Only one resource is reported to have a wrong hash. I think the problem is that this particular resource gets loaded with the `request` module of Node.js and not with the browser connector. It's the only resource which goes through this code path in my example.

https://github.com/webhintio/hint/blob/master/packages/hint-sri/src/hint.ts#L422

My server only returns the resources encoded with GZIP but the `request` module doesn't decode GZIP content. The browser on the other hand does.

Do you think it's feasible to replace the `request` module with the connector that is otherwise used to download resources?

**Comment by molant** [comment]
Hi @chrisguttandin,

Thanks for identifying the issue and sorry for my delayed response, we are in the middle of a big refactor and some internal stuff and completely missed this 😞

I've created https://github.com/webhintio/hint/issues/2068 to track your issue.
