### ISSUE TITLE
Force a cache clean and bypass service workers when possible

### ISSUE THREAD

**Issue by bmt-systems** [webhintio/hint#2928]
Windows 8.1
Canary 78 and Chrome 76
Webhint Extension 0.0.7

I'm using the suggested Apache .htaccess configuration, yet this hint is thrown for the webmanifest. It's once again appending the charset to the content-type; reason unknown.

> hint 1: 'content-type' header value should not contain 'charset=utf-8'.
> https://thomasbrodhead.com/favicons/site.20190904080058.webmanifest
> Content-Type: application/manifest+json; charset=utf-8

Is this related to Issue #2927?

**Comment by molant** [comment]
I've been trying to repro this in a clean laptop and I can't.

I'm starting to believe some of the problems we see with webhint might be related to the service worker you have. I've been capable of having a consistent (?) x-content-type error when running it from the service worker but not with a clean cache. This could explain some of the issues you are seeing.

@antross when we do a refresh from the extension I believe we request it from a clean cache but does that take into account sw? Is there an API we could use to by pass it if not?


________________________________

**Comment by bmt-systems** [comment]
You can disengage the Service Worker on that site by pressing Ctrl+Alt+S. A
confirmation message will then appear in the console. Then try running
Webhint on the site and see if there's a difference.

**Comment by bmt-systems** [comment]
(There's a mistake in the message above; it's Ctrl+Alt+s, meaning a lower case "s". But see the following):

The service worker at https://thomasbrodhead.com may be stopped and its caches flushed by clicking inside the browser window and then depressing Ctrl+Alt+s (lowercase s). The console will report:

> Ctrl+Alt+s: Delete caches and unregister service worker

If you don't see that message in the console, with the console open click the browser window and then depress Ctrl+Alt+s again.

If I run the Webhint extension analysis on the site after unregistering the service worker (and while in Incognito Mode), the following slew of hints are generated:

> hint 1: Response should include 'x-content-type-options' header.
> https://thomasbrodhead.com/sw.min.20190904070518.js
> hint 2: Response should include 'x-content-type-options' header.
> https://thomasbrodhead.com/javascript/jquery.min.map
> hint 3: Response should include 'x-content-type-options' header.
> https://thomasbrodhead.com/javascript/lightbox.min.map
> hint 4: Response should include 'x-content-type-options' header.
> https://thomasbrodhead.com/javascript/sizzle.min.map
> 

Webhint would be refreshing the site when it performs its analysis in some way, for the service worker is restarting during the webhint analysis. But this is different from running the webhint analysis with the service worker already active, for if I then perform a hard-refresh of the site (just to be sure the service worker is running) and then run the Webhint extension analysis on the site, only 1 hint is generated:

> hint 1: Response should include 'x-content-type-options' header.
> https://thomasbrodhead.com/sw.min.20190904070518.js
> 

This seems to suggest something is afoot with the service worker.

**Comment by molant** [comment]
After syncing with @antross we are going to use the [`browsingData`](https://developer.chrome.com/extensions/browsingData) API to clean the cache and service workers right before the reload.
The [MDN documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData) doesn't say anything about service worker support for Firefox so we might have to feature detect if that method is supported or not before calling it.

**Comment by molant** [comment]
@bmt-systems I've created #2937 that hopefully fixes this. That PR also has a packaged extension. Could you please test it and confirm it works in your end?

Some things I've found out:

* There are some images that have `x-content-type-options` missing. They only show up if you start the analysis when scrolled to the bottom of the page
* The service worker seems to download the favicon and that causes a double hit (I'm thinking we should ignore data coming from a SW but haven't found a way yet to do it)

**Comment by bmt-systems** [comment]
Here's what I get using the production (release) Webhint extension 0.0.7 vs the "beta" version from the repo.

I've tested https://thomasbrodhead.com in Incognito mode in both Chrome 76 and Canary 78, using both versions of the extension.

In each case, I've made the following settings on the scans:

> Target Browsers:
> * defaults, not IE 11
> 
> Ignored Resources:
> * Different Origin
> 

 WEBHINT BETA:
------------------
Chrome 76:
----------

> Security:
> hint 1: Response should include 'x-content-type-options' header.
> https://thomasbrodhead.com/sw.min.20190905062815.js

Canary 78:
----------

> Compatibility:
> hint 1: 'content-type' header value should not contain 'charset=utf-8'.
> https://thomasbrodhead.com/favicons/site.20190905165405.webmanifest
> Content-Type: application/manifest+json; charset=utf-8
> 
> Performance:
> hint 1: Static resources should use the "immutable" directive: Directives used: max-age=31536000,
> https://thomasbrodhead.com/favicons/favicon.20190811163149.ico
> Cache-Control: max-age=31536000,


WEBHINT PRODUCTION:
---------------------------
Chrome 76
---------

> Compatibility:
> hint 1: 'content-type' header value should not contain 'charset=utf-8'.
> https://thomasbrodhead.com/favicons/site.20190905165405.webmanifest
> Content-Type: application/manifest+json; charset=utf-8
> 
> Security:
> hint 1: Response should include 'x-content-type-options' header.
> https://thomasbrodhead.com/sw.min.20190905062815.js


Canary 78:
----------

> Compatibility:
> hint 1: 'content-type' header value should not contain 'charset=utf-8'.
> https://thomasbrodhead.com/favicons/site.20190905165405.webmanifest
> Content-Type: application/manifest+json; charset=utf-8
> 
> Performance:
> hint 1: The directive is invalid
> https://thomasbrodhead.com/favicons/favicon.20190811163149.ico
> Cache-Control: max-age=31536000,

**Comment by bmt-systems** [comment]
See "Edit" comment at top of my previous message; I had accidentally reversed the Canary and Chrome results in the listing for the Beta version of the extension, now corrected.

**Comment by molant** [comment]
With Chrome 76 I'm getting 

> Security:
hint 1: Response should include 'x-content-type-options' header.
https://thomasbrodhead.com/sw.min.20190905062815.js

> Performance:
hint 1: Static resources should use the "immutable" directive: Directives used: max-age=31536000,
https://thomasbrodhead.com/favicons/favicon.20190811163149.ico
Cache-Control: max-age=31536000,

I also get 4 requests to the sw file and one of those doesn't have the header:

![image](https://user-images.githubusercontent.com/606594/64449747-7ac5d200-d095-11e9-874b-b3b39dcdb34c.png)


I'm going to try to identify requests coming from the sw and ignore them directly. I think I'll try to do that at the connector level.
Another option is to ignore `304` requests but not sure where to ignore them: connector? specific hints?

@antross what do you think?

**Comment by molant** [comment]
@bmt-systems I've updated the PR and the bundles in it. Right now I'm ignoring requests coming from service workers and I'm not getting any duplication.
I can't still repro your manifest issue but I'm hoping this fixes it.

Do you mind testing it again?
Thanks!

**Comment by bmt-systems** [comment]
I can't find the link to the ZIP file of the beta for the extension. What is the URL to the page with the link?

**Comment by molant** [comment]
It's in the PR, I've updated the previous links.

Chromium one should be https://github.com/webhintio/hint/files/3585809/webhint-0.0.7.zip

Filename is the same so make sure to delete the other one to make sure you are using the right one.

Thanks!


________________________________

**Comment by bmt-systems** [comment]
Many thanks! I've put it through the paces. And...success! No service worker hints this time, so that seems to be solved. 

I'm still getting these errors, though, one in Chrome 76, it and another in Canary 78; perhaps start a new issue for these (or are they relative to the other open issues?)

```
Configurations
----------------
Target Browsers: defaults, not IE11
Ignored resources: Different Origin

```
Chrome 76.0.3809.132
-------------------------

> **Compatibility**
> hint 1: 'content-type' header value should not contain 'charset=utf-8'.
> https://thomasbrodhead.com/favicons/site.20190905165405.webmanifest
> Content-Type: application/manifest+json; charset=utf-8
> 

Canary 78.0.3904.5 
---------------------

> **Compatibility**
> hint 1: 'content-type' header value should not contain 'charset=utf-8'.
> https://thomasbrodhead.com/favicons/site.20190905165405.webmanifest
> Content-Type: application/manifest+json; charset=utf-8
> 

> **Performance**
> hint 1: Static resources should use the "immutable" directive: Directives used: max-age=31536000,
> https://thomasbrodhead.com/favicons/favicon.20190811163149.ico
> Cache-Control: max-age=31536000,

**Comment by molant** [comment]
Glad that we fixed some stuff.

The issue about inmutable for the favicon is valid and I get it on any chrome version on my side so let's concentrate on the Manifest one and we can look later why you are not getting it in Chrome 76.

I can't repro the Manifest one so let's try a couple things:

1. If you haven't already, try disabling all other extensions except webhint and give it a try. If things changed we will need to pinpoint which one is causing this so a list will be helpful if you don't mind sharing it

2. Independently of the above, before running webhint can you go to the network panel so it starts recording and then run webhint? Then filter the network requests so only the Manifest ones are there, and let me know how many there are and what are their response headers.

Thank you!






________________________________

**Comment by bmt-systems** [comment]
I've been using Webhint alone with no other extensions active in Incognito Mode, so No. 1 is covered.

I performed the steps you asked (I believe I did them right, but you can judge from the screen shots), and here they are:

Pic 1:
I open the site in Chrome 76 in Incognito mode with only Webhint active as an extension. I hard-refresh the site, which shows that the service worker has been refreshed in the console.
![01](https://user-images.githubusercontent.com/32374938/64476481-d4d99c80-d154-11e9-9f0e-c0917cccedd8.jpg)

Pic 2:
I open the Network tab and pre-select Manifest.
![02](https://user-images.githubusercontent.com/32374938/64476493-e91d9980-d154-11e9-8c79-7201ff23248f.jpg)

Pic 3:
I select the same options as before for Webhint.
![03](https://user-images.githubusercontent.com/32374938/64476501-fcc90000-d154-11e9-93d7-b42c33c77c0f.jpg)

Pic 4:
I run Webhint and receive the Manifest hint:
![04](https://user-images.githubusercontent.com/32374938/64476512-110cfd00-d155-11e9-9f64-314398a9fd9f.jpg)

Pic 5:
I switch to the Network tab and see no activity under Manifest:
![05](https://user-images.githubusercontent.com/32374938/64476517-271abd80-d155-11e9-9db0-a6430b7a6a15.jpg)

Pic 6:
I select all resources and discover everything else has loaded with a 200 response:
![06](https://user-images.githubusercontent.com/32374938/64476528-3a2d8d80-d155-11e9-9f27-6519032e454c.jpg)

Have I missed a step? Can you reproduce these steps and these results?

**Comment by molant** [comment]
🤔

What about typing "manifest" in the filter box instead of selecting the type of resource?
Does it show anything?


________________________________

**Comment by bmt-systems** [comment]
Aha! That does the trick:
![07](https://user-images.githubusercontent.com/32374938/64477120-4c132e80-d15d-11e9-88e3-3dd89c18560c.jpg)

**Comment by molant** [comment]
Can you click (or double click?) on that item and show me the headers? They should show up on the right side.


________________________________

**Comment by bmt-systems** [comment]
Yes, two screen captures to show the entire listing:
![08](https://user-images.githubusercontent.com/32374938/64478058-4bcc6080-d168-11e9-98f6-034ec1a14f0f.jpg)
![09](https://user-images.githubusercontent.com/32374938/64478062-525ad800-d168-11e9-8350-3d28b60ba864.jpg)

**Comment by bmt-systems** [comment]
^ The code from the default .htaccess file I provided earlier (as an edit to the first set of images I sent) clearly shows a utf-8 header for webmanifest files; why is Webhint throwing the hint if the suggested .htaccess sends it? Is the suggested .htaccess code incorrect?

**Comment by molant** [comment]
It looks like the Manifest comes from disk and sec-fetch-mode is set to cors which I have no idea why.

Do you have the site installed?

If you go to the "Application" tab and delete all the related information (including SW) can you still reproduce the issue?


________________________________

**Comment by bmt-systems** [comment]
Let me recompile the site with the service worker inactive altogether and try again. One minute....

**Comment by bmt-systems** [comment]
I recompiled the site so the service worker was not active at all. The cache storage and the application cache are both empty. Webhint reports the same hint for the webmanifest file. Here are screenshots of the resourc
![11](https://user-images.githubusercontent.com/32374938/64478548-766de780-d16f-11e9-9342-61c0f168481c.jpg)
e:
![10](https://user-images.githubusercontent.com/32374938/64478542-66560800-d16f-11e9-8994-37ce4abffa94.jpg)

**Comment by bmt-systems** [comment]
Wait: I just tried running Webhint in Chrome standard mode (not Incognito), and the hint is not present! It only occurs when I open the site in Incognito mode and run Webhint there. I was expecting that the standard mode might have cached the webmanifest, and Incognito was somehow sensing it. But that's not the case. Pics of headers in standard mode:
![12](https://user-images.githubusercontent.com/32374938/64478638-8e923680-d170-11e9-81aa-d94e8df4536d.jpg)
![13](https://user-images.githubusercontent.com/32374938/64478639-92be5400-d170-11e9-9ffb-578c533479d6.jpg)

**Comment by molant** [comment]
I'm on phone but those look like the same as before, right? But webhint doesn't report in this case? 🤯

I'll give it a try when I'm back at work in incognito mode, hopefully I can repro it now and find what's going on.

In any case I'm glad that you are now getting the right results!


________________________________

**Comment by molant** [comment]
@bmt-systems if I run in incognito I can repro your issue with the `charset=utf-8`. Hope to find something soon-ish

**Comment by molant** [comment]
@antross and I've been working on a fix for this issue and the PR is now updated.
The chromium bundle with the change should be available in https://github.com/webhintio/hint/files/3592792/webhint-0.0.7.zip

If you are curious, incognito mode doesn't download the manifest automatically so we "manually" download it. The problem was that we weren't populating some of the internal information we are using from the request and thus causing the hint to fail.

**Comment by bmt-systems** [comment]
Success! The hint is no longer triggered in Incognito mode, neither in Chrome 76 nor Canary 78 when I test it.

That leaves the following to be resolved:

> hint 1: Static resources should use the "immutable" directive: Directives used: max-age=31536000,
> https://thomasbrodhead.com/favicons/favicon.20190811163149.ico
> Cache-Control: max-age=31536000,

This hint is triggered in standard mode ONLY in Chrome 76; the hint is not triggered in Incognito mode in Chrome 76.

This hint is triggered in BOTH standard mode and Incognito mode in Canary 78.

Should this be logged as a separate issue, or should we continue on this thread?

**Comment by molant** [comment]
because flagging is the right behavior and it seems that chrome 78 fixes this, I'm more inclined to believe that we are facing a chromium bug that has already been fixed and will reach stable in the next few weeks.

What do you think of creating a new issue and wait until Chrome 78 reaches stable?

**Comment by bmt-systems** [comment]
This is where I'm confused. Is the hint actually _not_ in error? I.e., is there an error with the directives in my .htaccess file, and the hint is actually doing the right thing in alerting me to it? If so, what needs to be changed? This is what I have, taken from the Webhint recommend settings:

```
<IfModule mod_expires.c>
    ExpiresActive on
    ExpiresDefault                                   "access plus 1 year"
        ExpiresByType text/cache-manifest            "access plus 0 seconds"
        <Files "favicon.ico">
            ExpiresByType image/x-icon               "access plus 1 year"
        </Files>
        ExpiresByType application/atom+xml           "access plus 1 hour"
        ExpiresByType application/rdf+xml            "access plus 1 hour"
        ExpiresByType application/rss+xml            "access plus 1 hour"

        ExpiresByType application/json               "access plus 0 seconds"
        ExpiresByType application/ld+json            "access plus 0 seconds"
        ExpiresByType application/schema+json        "access plus 0 seconds"
        ExpiresByType application/vnd.geo+json       "access plus 0 seconds"
        ExpiresByType text/xml                       "access plus 0 seconds"
        ExpiresByType text/html                      "access plus 0 seconds"
    <IfModule mod_headers.c>
        Header merge Cache-Control immutable
        <FilesMatch "\.(appcache|cur|geojson|ico|json(ld)?|x?html?|topojson|xml)$">
            Header edit Cache-Control immutable ""
        </FilesMatch>
    </IfModule>
</IfModule>

```

**Comment by molant** [comment]
The favicon should be served with `immutable`. It's an static resource and you are already cache busting it.

````xml
<Files "favicon.ico">
    ExpiresByType image/x-icon               "access plus 1 year"
</Files>
```

This only applies to  `favicon.ico` and you have something like `favicon.123456.ico`. I think you can revert it back to whatever was which should be a few hours/days?

```xml
Header merge Cache-Control immutable
<FilesMatch "\.(appcache|cur|geojson|ico|json(ld)?|x?html?|topojson|xml)$">
    Header edit Cache-Control immutable ""
</FilesMatch>
```

I believe `FilesMatch` in above are rewriting again the `immutable` part to be replaced with `""`. Try removing the `.ico` part in the regular expression see if you get the header.

**Comment by bmt-systems** [comment]
Ah, got it! So, if I want to continue cache-busting the ico, there's no need to include it in the directive.

And, success! Removing it from the regex eliminates the hint both in the extension and in the online scanner.

The only thing remaining is a hint the online scanner presents:

> hint #1: Response should not be compressed for requests made with 'accept-encoding: identity'.
> https://thomasbrodhead.com/javascript/master.min.20190908222614.js
> 

What am I setting incorrectly in this .htaccess code, taken from the Webhint boilerplate?

```
<IfModule mod_headers.c>
    <IfModule mod_rewrite.c>
        RewriteEngine On
        Options +FollowSymlinks
            RewriteCond "%{HTTP:Accept-encoding}" "br"
            RewriteCond "%{HTTPS}" "on"
            RewriteCond "%{REQUEST_FILENAME}\.br" "-s"
            RewriteRule "^(.*)" "$1\.br" [QSA]
            RewriteRule "\.(ico|cur)\.br$"      "-" [T=image/x-icon,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.(md|markdown)\.br$"  "-" [T=text/markdown,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.appcache\.br$"       "-" [T=text/cache-manifest,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.atom\.br$"           "-" [T=application/atom+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.bmp\.br$"            "-" [T=image/bmp,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.css\.br$"            "-" [T=text/css,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.eot.\.br$"           "-" [T=application/vnd.ms-fontobject,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.geojson\.br$"        "-" [T=application/vnd.geo+json,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.html?\.br$"          "-" [T=text/html,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.ics\.br$"            "-" [T=text/calendar,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.json\.br$"           "-" [T=application/json,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.jsonld\.br$"         "-" [T=application/ld+json,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.m?js\.br$"           "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.otf\.br$"            "-" [T=font/otf,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.rdf\.br$"            "-" [T=application/rdf+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.rss\.br$"            "-" [T=application/rss+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.svg\.br$"            "-" [T=image/svg+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.ttc\.br$"            "-" [T=font/collection,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.ttf\.br$"            "-" [T=font/ttf,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.txt\.br$"            "-" [T=text/plain,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.vc(f|ard)\.br$"      "-" [T=text/vcard,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.vtt\.br$"            "-" [T=text/vtt,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.webmanifest\.br$"    "-" [T=application/manifest+json,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.xhtml\.br$"          "-" [T=application/xhtml+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.xml\.br$"            "-" [T=text/xml,E=no-brotli:1,E=no-gzip:1]
            <FilesMatch "\.br$">
                Header append Content-Encoding br
            </FilesMatch>
            RewriteCond "%{HTTP:Accept-encoding}" "gzip"
            RewriteCond "%{REQUEST_FILENAME}\.gz" "-s"
            RewriteRule "^(.*)" "$1\.gz" [QSA]
            RewriteRule "\.(ico|cur)\.gz$"      "-" [T=image/x-icon,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.(md|markdown)\.gz$"  "-" [T=text/markdown,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.appcache\.gz$"       "-" [T=text/cache-manifest,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.atom\.gz$"           "-" [T=application/atom+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.bmp\.gz$"            "-" [T=image/bmp,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.css\.gz$"            "-" [T=text/css,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.eot.\.gz$"           "-" [T=application/vnd.ms-fontobject,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.geojson\.gz$"        "-" [T=application/vnd.geo+json,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.html?\.gz$"          "-" [T=text/html,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.ics\.gz$"            "-" [T=text/calendar,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.json\.gz$"           "-" [T=application/json,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.jsonld\.gz$"         "-" [T=application/ld+json,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.m?js\.gz$"           "-" [T=text/javascript,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.otf\.gz$"            "-" [T=font/otf,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.rdf\.gz$"            "-" [T=application/rdf+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.rss\.gz$"            "-" [T=application/rss+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.svg\.gz$"            "-" [T=image/svg+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.ttc\.gz$"            "-" [T=font/collection,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.ttf\.gz$"            "-" [T=font/ttf,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.txt\.gz$"            "-" [T=text/plain,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.vc(f|ard)\.gz$"      "-" [T=text/vcard,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.vtt\.gz$"            "-" [T=text/vtt,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.webmanifest\.gz$"    "-" [T=application/manifest+json,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.xhtml\.gz$"          "-" [T=application/xhtml+xml,E=no-brotli:1,E=no-gzip:1]
            RewriteRule "\.xml\.gz$"            "-" [T=text/xml,E=no-brotli:1,E=no-gzip:1]
            <FilesMatch "\.gz$">
                Header append Content-Encoding gzip
            </FilesMatch>
        <FilesMatch "\.(br|gz)$">
            Header append Vary Accept-Encoding
        </FilesMatch>
    </IfModule>
</IfModule>

<IfModule mod_deflate.c>
    <IfModule mod_filter.c>
        AddOutputFilterByType DEFLATE "application/atom+xml" \
                                      "application/json" \
                                      "application/manifest+json" \
                                      "application/rdf+xml" \
                                      "application/rss+xml" \
                                      "application/schema+json" \
                                      "application/vnd.ms-fontobject" \
                                      "application/xhtml+xml" \
                                      "font/collection" \
                                      "font/opentype" \
                                      "font/otf" \
                                      "font/ttf" \
                                      "image/bmp" \
                                      "image/svg+xml" \
                                      "image/x-icon" \
                                      "text/cache-manifest" \
                                      "text/css" \
                                      "text/html" \
                                      "text/javascript" \
                                      "text/plain" \
                                      "text/vtt" \
                                      "text/xml"
    </IfModule>
    <IfModule mod_mime.c>
        AddEncoding gzip              svgz
    </IfModule>
</IfModule>

```

**Comment by molant** [comment]
Mind if we continue the conversation about `Accept-Encoding` to https://github.com/webhintio/hint/issues/2919#issuecomment-529037950 ?

I provided some feedback last Friday and we can go from there to figure out why it only flags that file and not other scripts you have in the site.

**Comment by bmt-systems** [comment]
Sure, please.
