### ISSUE TITLE
Improve speed when using sonarwhal globally

### ISSUE THREAD

**Issue by molant** [webhintio/hint#896]
If you install `sonarwhal` globally it takes a lot of time to load, even for the most basic thing like `sonarwhal -v`. 
We need to investigate where the bottle neck is. This doesn't seem to happen when installed as a dependency so it might be related to something like finding configuration files, resources, etc.

**Comment by sarvaje** [comment]
After a lot of tests, I have extracted this table:


  | # Require* | Time (ms)
-- | -- | --
Global | 8017 | 6796.469
Global** | 6274 | 5650.207
Local | 8017 | 6658.993
Local** | 6274 | 5449.231
Project folder | 4551 | 3994.879
Yarn Local | 6032 | 5053.236

\* Total number that require is called.
\** After deleting sonarwhal from `sri` and `no-bom` rules.

These values are taken from the beginning until just before start to analyze a web site.

As you can see, the lowest the number of request, the lowest the time it takes.

The problem I found was that a couple of rules (`sri` and `no-bom`) are installing sonarwhal in their own package, and that consequently is increasing a lot the number of request to `require`, because those rules has to load their own version of sonarwhal, instead of using the main one.

This can be caused because the latest versions of those rules has configured `sonarwhal 1.5.0` but the current version of sonarwhal is `1.6.0`. But anyway I don't know why `npm` is installing it, because it is configure as a `devDependency` and a `peerDependency`.

As you can see, the difference of requests is still huge, and that is because of how `npm` install the dependencies. Instead of sharing packages (as we do in the project folder), `npm` is installing all the dependencies in each package.

The number of request using `yarn` is a little bit lower because `yarn` share more packages than `npm`.

**Comment by molant** [comment]
Can you update those packages to the latest version?

I'll try to publish a new version later this week and hopefully we should see some improvements in the published version.


________________________________

**Comment by sarvaje** [comment]
They are updated in the project, but the changes are not published.

**Comment by alrra** [comment]
> They are updated in the project, but the changes are not published.

@sarvaje I'll publish a new version of those packages. :)

**Comment by alrra** [comment]
>> They are updated in the project, but the changes are not published.
>
> @sarvaje I'll  publish a new version of those packages.

Done.

**Comment by TheLarkInn** [comment]
I'm also happy to advise along the way.

**Comment by molant** [comment]
It looks like we are having issues with TypeScript and yarn workspaces when building and switching to `esnext` modules instead of `commonjs`. We are not the only ones:
* https://github.com/Quramy/lerna-yarn-workspaces-example#resolve-dependencies-as-typescript-modules
* https://www.developertown.com/example-typescript-monorepo-part-1-react-native/

Basically the recommendation seems to be to use [`paths` in `tsconfig.json`](http://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping) but I'm having trouble making it work 😔

Another option would be to use the [`nohoist` option from yarn](https://yarnpkg.com/blog/2018/02/15/nohoist/) for the packages that are only part of `packages/sonarwhal` and not shared (this would generate an output similar to what `npm` does when we publish).

@sonarwhal/contributors has anyone had a similar problem in the past? Any recommendations?

**Comment by molant** [comment]
Some progress with webpack, I've managed to compile the CLI (problem was `moduleResolution` wasn't `node`) and in `production` mode the size is 2.16MiB 🎉 (there are a few packages that might still need to be downloaded)

![image](https://user-images.githubusercontent.com/606594/40513336-462a4bdc-5f5a-11e8-992a-f03dfc6be910.png)

Project still doesn't work but size wise it's a huge improvement to what we are shipping right now taking into account the dependencies.

**Comment by molant** [comment]
Another thing we can do to improve the load speed (regardless of it is local or global):

Right now the cli allows to create `new-rule`, `new-parser`, `init`, etc. and we are loading all the dependencies of these tasks even though we are only going to execute one. The idea is to use dynamic imports to only load what's necessary in each case.

I'll start working on this.

**Comment by molant** [comment]
Original graph using `require-so-slow` to instrument the `require`s until [this moment in cli.ts](https://github.com/sonarwhal/sonarwhal/blob/58a9416a374b2887e4076f66b7df18f90298a9b9/packages/sonarwhal/src/lib/cli.ts#L83):

![image](https://user-images.githubusercontent.com/606594/40559405-45a4d624-601c-11e8-88dd-bf1cef7cd4ca.png)

Total `require`s: 3018
Time: ~4.4s

And this is the one with lazy loading:

![image](https://user-images.githubusercontent.com/606594/40559541-b80cf732-601c-11e8-9830-51d4f227fa77.png)

Total `require`s: 936
Time: ~1.3s

**Comment by molant** [comment]
Moving the discussion about webpack to its own issue in #1102

**Comment by molant** [comment]
I think we've improved quite a lot the speed compared to previous version with all the splitting and lazy loading. Closing this.
